cfg: store slot info into U-Boot env when updating the startup DS
This is in preparation for fixing that long-standing problem with A/B
config slots.

Bug: https://github.com/CESNET/velia/issues/20
Change-Id: Id4951a86748bbd4a0df2051086a7960400769ae3

diff --git a/package/czechlight-cfg-fs/impl-cfg-save-sysrepo b/package/czechlight-cfg-fs/impl-cfg-save-sysrepo
--- a/package/czechlight-cfg-fs/impl-cfg-save-sysrepo
+++ b/package/czechlight-cfg-fs/impl-cfg-save-sysrepo
@@ -22,4 +22,17 @@ else
     # ...and then move it atomically.
     mv ${NEW_COPY} ${CONFIG_FILE}
     sync ${CONFIG_FILE}
+
+    if grep -q rauc.slot=A /proc/cmdline; then
+        RAUC_CURRENT_SLOT=A
+    elif grep -q rauc.slot=B /proc/cmdline; then
+        RAUC_CURRENT_SLOT=B
+    else
+        echo "Cannot determine active RAUC slot"
+        exit 1
+    fi
+    CFG_LAST_SLOT=$(fw_printenv CFG_LAST_SLOT)
+    if [[ "${RAUC_CURRENT_SLOT}" != "${CFG_LAST_SLOT}" ]]; then
+        fw_setenv CFG_LAST_SLOT ${RAUC_CURRENT_SLOT}
+    fi
 fi
